### ISSUE TITLE
Dynamic links filtering

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#202]
We can do something like this in order to make it easier to mention fragments/authors/etc once the DB grows more: https://www.w3schools.com/howto/howto_js_filter_dropdown.asp

**Comment by tcouch** [comment]
I think a datalist element would be simpler option as there's no js required:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

**Comment by tcouch** [comment]
Order selection by numerical reference rather than order added to the database.

**Comment by tcouch** [comment]
Update on this from today's meeting:
* Need to order by numerical reference rather than order added to database reiterated
* I suggested being able to us letters UATF and a number as shorthand
* We're unsure if testimonia are searchable in this way. If they're not, we need to add them.

**Comment by tcouch** [comment]
# @mention shortcut syntax proposal

## Current behaviour

"@<wbr>find me": searches for "find me" in all of:
    * Antiquarian name
	* Bibliography authors
	* Bibliography title
	* Topic name
	* Work name
	* Fragments' related antiquarians' names
	* Testimoniums' related antiquarians' names
	
@<wbr>f\<int>: Searches for Anonymous fragments with order <int> - 1 (their display name is order + 1). Also unnecessarily runs all other search methods.

@<wbr>u\<int>: Searches for Unlinked fragments with id starting with <int>; e.g. @<wbr>u12 matches Unlinked12, Unlinked123, Unlinked124. Also unnecessarily runs all other search methods.

## Proposed behaviour

Backend:
* All @<wbr>mention searches should begin with a two letter short code indicating the target model type
* Remove blanket search - choose search method based on initial two-letter code
* Instead of treating everything after the @ symbol as one keyword to match exactly, allow users to enter multiple keywords separated by colon character; e.g. @<wbr>aq:marcus:varro
* Move sorting to search methods so we can tune it to the search method

Frontend:
* No ajax request is sent until the user types at least two characters after the @ symbol
* Introduce a one second pause after each keystroke before sending an ajax request so we don't have a separate request for each character
* Short code reminder in mouseover text below text editor where it says "@<wbr>mentions are enabled"


| Model              | Short code | Sort by              | Example    |
|--------------------|------------|----------------------|------------|
| Antiquarian        | @<wbr>aq        | order_name desc      | @<wbr>aq:varro  |
| Bibliography       | @<wbr>bi        | author_surnames desc | @<wbr>bi:jones  |
| Topic              | @<wbr>tp        | topic order          | @<wbr>tp:war    |
| Work               | @<wbr>wk        | name                 | @<wbr>wk:musica |
| Fragment           | @<wbr>fr        | pk (or order_year?)  | @<wbr>fr:varro  |
| Anonymous Fragment | @<wbr>af        | order                | @<wbr>af:12     |
| Testimonium        | @<wbr>tt        | pk                   | @<wbr>tt:varro  |
| Unlinked Fragment  | @<wbr>uf        | pk                   | @<wbr>uf:123    |

**Comment by tcouch** [comment]
@rmamarshall what do you think of this approach to handling @mentions? Would there be times perhaps where you'd want to be able to search all content types?

**Comment by rmamarshall** [comment]
@tcouch 
Hi Tom! I think this would work well, but the short code reminder popup will be crucial. To clarify, will this be displayed every time someone types @ into the database? (I think this would be an absolute necessity, along with a few lines of text that give examples of / explain how to construct searches).

For linking to Antiquarians, Bibliography, Topic, and Work this will be a great improvement over the current system (also the ability to link to testimonia!). However, I'm unsure how the new version helps us solve our other big problem: currently, '@varro' brings up 600 unsorted fragment entries (fragments appear in the order entered, not in numerical sequence); the correct entry then needs to be hunted down in a giant random list.
 
Would a search like @fr:varro:123 work? (i.e., the search takes one immediately to Varro fr. 123?). If there are two entitites with F123 in their description, obviously both should be displayed (E.g. Varro, de musica F1 - Varro F123; Varro, de philosophia F123 = Varro F497).

As we always have a definite target in mind when making links, I can't imagine that we would need / want to search all content types. This is esentially the system we have at the moment, and is increasingly challenging to use.

**Comment by tcouch** [comment]
@rmamarshall I think a search like @fr:varro:123 could work. The function that parses the search term could apply a simple rule for fragments where any text is assumed to be the related antiquarian's name, and any numbers are assumed to refer to the fragment's order with respect to a work or antiquarian.

Re the reminder: It'd be a matter of providing useful information without cluttering up the user interface with too much text. I'll see what we can squeeze into a pop up. We'll write a more detailed explanation anyway and add it to the documentation.

**Comment by tcouch** [comment]
This needs documenting in the wiki
