### ISSUE TITLE
Convert an ‘Unlinked’ fragment to ‘Anonymous’ and vice versa

### ISSUE THREAD

**Issue by stephencblair** [UCL/frrant#231]
Strange as it sounds, we occasionally change our minds about whether a fragment is ‘anonymous’ or not (most commonly when we reconsider whether to label something as a proper fragment of an antiquarian, or as an anonymous ‘appositum’ to that antiquarian’s other material). However, anonymous fragments in the database are in their own special category: once a fragment has been created as ‘anonymous’ it can never be attributed to an antiquarian, as ‘unlinked’ fragments can; likewise, a fragment once attributed to somebody can never be made anonymous (if it has no attribution, it becomes ‘unlinked’).

Could anonymous fragments have the option to be made unlinked, and vice versa? Ideally, the edit page on an unlinked fragment could have a button ‘Make anonymous’, and the edit page on an anonymous fragment with no appositum links could have a button ‘Make unlinked’.

**Comment by tcouch** [comment]
Hi @stephencblair I've written some back-end functions which should be able to handle this conversion, but it'd be good to clarify a few things before I go any further. I've outlined the process for converting fragments in both directions below. Can you have a look and let me know if there's anything that doesn't sound right please?

## Converting an unlinked fragment to an anonymous fragment
I think this is the more straightforward part of this request. The conversion function will create a new anonymous fragment and assign all the relevant properties from the unlinked fragment to it, including:
* topics
* original texts (including translations, apparatus critici, concordances, citing work, reference, reference order)
* collection id
* name
* commentary
* order year
* data range

Once the new anonymous fragment has been created, the unlinked fragment will be deleted.

### Comments
* The "Convert to anonymous fragment" button will only appear when editing an unlinked fragment making it impossible to convert a linked fragment to an anonymous fragment without first removing all of its links
* This restriction will also be enforced by checks on the backend
* The changelogs for the fragment's components (e.g. original texts) will remain intact since they're attached to those components and not the fragment itself. 
* Fragments do have their own high-level changelog, which will be lost, but this only reflects changes to topics, chronological reference, and order year.
* This conversion is reversible, but the original unlinked fragment will have been deleted and its replacement will have a new display name due to the fact it has a new id number (e.g. Unlinked 300 -> Unlinked 500)

## Converting an anonymous fragment to a fragment
This is a bit more complicated because of the fact some anonymous fragments have appositum links, which I'm presuming need to be converted into fragment links. So, in addition to creating a new fragment with all the relevant properties copied from the anonymous fragment (as above), new fragment links will need to be created based on any appositum links from the anonymous fragment.

For each appositum link we copy its properties to a new fragment link including:
* antiquarian
* order
* definite (true/false is it a definite or possible link)
* work
* work order
* book

Appositum links also have an 'exclusive' property for which fragment links have no equivalent so this data will be lost.

The alternative to this of course is to only allow unlinked anonymous fragments to be converted to fragments, but I presume that's not what you're after since it's the anonymous fragments with appositum links that you're most likely to want to convert.

### Apposita for Unlinked Fragments
It's currently possible via the web interface to create apposita for unlinked fragments, or to create a link to an unlinked fragment from an anonymous fragment, but this has no discernible affect on the unlinked fragment's detail page. Inspecting the database it looks like no appositum link is created, but a direct relationship is created via the anonymous fragment's fragments field. There's currently no way to view or delete this relationship via the web interface once it's been established.
- Should it be possible to create apposita for Unlinked fragments at all?
- If so, how should they be displayed?
- and, what should happen to apposita for unlinked fragments when the unlinked fragment is converted to an anonymous fragment?

**Comment by raquelalegre** [comment]
This was demoed at last meeting. 

* This changes were demoed last week. All were approved, although there's a request to specify in the warning message when a fragment has apposita what will happen to the apposita after the conversion. 
* Apposita for unlinked fragments is not relevant at the moment, and it's intended all unlinked fragments disappear (because they'll become linked) as more data is discovered as part of the research.
