### ISSUE TITLE
Order anonymous section by reference number per topic

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#290]
.

**Comment by raquelalegre** [comment]
@ucravar and team have a new suggestion for ordering anonymous fragments by having the up/down arrows we have in topic ordering or works/fragments ordering. They'll need to think about how this is done best, and edge cases like what to do when a fragment belong to a topic that spans several pages, etc. Should we have a default sorting in the meanwhile? For example, sorting as is with the reference number sort corrected. Fragment sorting should only happen within each topic, ie a fragment of a given topic can't be moved to another topic - fragment<->topic relationship is only possible to establish via the fragment details edition.

**Comment by raquelalegre** [comment]
We also need to think how feasible this is and what the work entails. Front-end work can be based on what Peter did for the fragment order in the antiquarian pages. Back-end can be tricky as anon fragment IDs will change as fragments are moved up/down/dragged.

**Comment by tcouch** [comment]
After discussion in today's meeting it turns out that this issue can actually be split into two separate issues. The first, which most closely matches the title of this issue, is a request for users to be able to click a toggle to order the anonymous fragments by reference number rather than display name. This change would be for display purposes only and would not affect any properties of the anonymous fragments such as order or display name.

The second request is for users to be able to change the order of anonymous fragments with respect to topics, which would have an affect on their order values and display names (see #326)

**Comment by rmamarshall** [comment]
Currently, anonymous fragments seem to be ordered by reference number across rather than within authors. E.g.:
Livy 1.1; Gell. 1.2; Livy 1.3.
This should actually be displayed as:
Livy 1.1; Livy 1.3; Gell. 1.2.

**Comment by tcouch** [comment]
Created a new issue #378 to carry this on.
