### ISSUE TITLE
Issues with ordering and presentation of fragments within works

### ISSUE THREAD

**Issue by rmamarshall** [UCL/frrant#370]
@tcouch 

Hi Tom,
We've noticed that the order of fragments cannot be changed when 'edit' mode is switched on in the 'Works' section of the database, also that book numbers do not appear under works in the 'Antiquarians' section of database. 

Edit mode in 'Antiquarian' section:

![image](https://user-images.githubusercontent.com/75932472/210786307-67ad515a-6e24-4bb4-8e61-7e82725fb5cf.png)

Edit mode in 'Works' section:

![image](https://user-images.githubusercontent.com/75932472/210786486-22150ba5-e472-4ec9-a598-41c32f3644eb.png)

Ideally, the information available and functionality of the edit mode in the two different pages should be merged, i.e. all components (book numbers, testimonia, and the ability to re-order fragments and testimonia) should be shown / available in both pages. 

When 'edit mode' is turned off, we should also be able to see book numbers in the Antiquarians page and testimonia in the Works page.

Best wishes,
Richard

**Comment by tcouch** [comment]
@rmamarshall I think we'd need to have a chat about how ordering would work on the Works page given the fragments are not currently displayed in order with respect to the Work, but rather in separate sections by Book. For example _Marcus Terentius Varro: De vita populi Romani F11_ appears way down the page because it belongs to Book 2. 

Are you asking to be able to reorder fragments with respect to Books, or with respect to Works (as is currently possible on the Antiquarian pages)? The former would entail a significantly greater amount of effort as there's currently no mechanism to record and edit order with respect to books. If the latter, it would no longer make sense to display Fragments in separate sections by Book on the Works page (at least not while in edit mode) as a fragment with order N would not necessarily be displayed adjacent to the fragments with order N-1 and N+1. So, would you want us to add information about the Book a fragment belongs to within the fragment name somewhere - possibly something like _Marcus Terentius Varro: De vita populi Romani: Book 2 F11 [= Marcus Terentius Varro F11]_?

**Comment by rmamarshall** [comment]
@tcouch.
I'm not sure that I entirely follow you, but ideally we'd like to be able to reorder fragments within a particular book, or remove fragments from one book and assign them to another, or simply assign them to a work (where the book number is not known). For instance:

Work A
Book 1
A1
B1
C1
Book 2
A2
B2
C2
Book not known
A3
B3
C3

Where ABC = individual fragments which can always be ordered with respect to one another, but also be moved individually from Book 1 to Book 2, to Book not Known, or even to Work B.

As an additional refinement, we would need the ability to 'lock' a characteristic, i.e. if D1 is reported to belong to Work A, Book 1, it should only be possible to alter its position in relation to ABC of Book 1 (and not be possible to move it from Book 1 to Book 2, let alone to Work B). This information is already captured in the 'definite work and books' section: if a book number is not assigned, this should meant that a fragment is free to move between Book 1, Book 2, etc. as a 'possible fragment', even if it is automatically assigned to the 'Unknown Book' section by default.

**Comment by tcouch** [comment]
To do:
- [x] Add order_in_book attribute to WorkLinks
- [x] Write migration to derive order_in_book from current work_order
- [x] Automatically calculate antiquarian order and work order on save/update - might just work once frontend ordering is implemented
- [x] Make books orderable within works -- need to fix fragment ordering on ant detail page
- [x] Indicate definite/possible status in the user interface symbolically instead of using section headers
- [x] Implement re-ordering on the work detail page
- [ ] See where lockable object mixin is used - have it cascade, eg. when you unlock a work you unlock it's books, fragments and links 
- [ ] Make WorkLinkBase objects editable - maybe inline form for changing book/work
- [x] Redesign user interface - add in unlinked frags page

**Comment by acholyn** [comment]
-[] See where lockable object mixin is used - have it cascade, eg. when you unlock a work you unlock it's books, fragments and links

**Comment by rmamarshall** [comment]
@tcouch Hi Tom, 
As part of the work to reorganise the treatment of works and books, I thought it best to add the following request here. 
Would it be possible to add the ability to include a text box (like the 'introductions' box for an antiquarian / comment box for a fragment) with each work and book? This box would sit below a title and before any testimonia / fragments, and could be edited from the 'works' page like other details. Bibliography would be associated with the antiquarian to which the work is attributed.

**Comment by rmamarshall** [comment]
@tcouch Hi Tom, 
As part of the work to reorganise the treatment of works and books, I thought it best to add the following request here. 
Would it be possible to add the ability to include a text box (like the 'introductions' box for an antiquarian / comment box for a fragment) with each work and book? This box would sit below a title and before any testimonia / fragments, and could be edited from the 'works' page like other details. Bibliography would be associated with the antiquarian to which the work is attributed.
